version: '3'
services:
  backend:
    build:
      context: ./backend/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: node server.js

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    command: npm run serve
